INSERT INTO marketplace (
    name,
    logo,
    status,
    commission_rate,
    integration_type,
    api_endpoint,
    created_at,
    updated_at
) VALUES
(
    'Mercado Livre',
    'https://grandesnomesdapropaganda.com.br/wp-content/uploads/2021/04/Mercado-Livre.jpg',
    'active',
    0.16,
    'api',
    'https://api.mercadolibre.com',
    NOW(),
    NOW()
),
(
    'Shopee',
    'https://logodownload.org/wp-content/uploads/2021/03/shopee-logo-0.png',
    'active',
    0.18,
    'api',
    'https://partner.shopeemobile.com/api/v2',
    NOW(),
    NOW()
),
(
    'Amazon',
    'https://logodownload.org/wp-content/uploads/2014/04/amazon-logo-0.png',
    'inactive',
    0.15,
    'manual',
    NULL,
    NOW(),
    NOW()
),
(
    'PDV',
    'https://logodownload.org/wp-content/uploads/2021/03/shopee-logo-0.png',
    'active',
    0.10,
    'api',
    'https://partner.shopeemobile.com/api/v2',
    NOW(),
    NOW()
);