
services:
  mysql:
      image: mysql:8.0
      container_name: kenjix_estoque_mysql
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE_KENJIX}
      volumes:
        - mysql_data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      networks:
        - kenjix_net
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_DATABASE_KENJIX}", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 5s
        timeout: 5s
        retries: 10

  flyway:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    container_name: kenjix_flyway
    volumes:
      - ../db/migration:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE_KENJIX}
      FLYWAY_USER: ${MYSQL_ROOT_PASSWORD}
      FLYWAY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - kenjix_net

networks:
  kenjix_net:
    driver: bridge
volumes:
  mysql_data: