version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: kenjix_postgres
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    command: migrate
    container_name: kenjix_flyway
    volumes:
      - ./db/migration:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/estoque
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
    depends_on:
      - postgres

  api:
    build:
      context: .. 
      dockerfile: docker/Dockerfile    
    container_name: kenjix_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
